services:
  influxdb2:
    image: influxdb:2.7.12
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - smarthouse-net

  grafana:
    image: grafana/grafana:12.2
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - smarthouse-net
    depends_on:
      - influxdb2

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  smarthouse-net:
    driver: bridge
