AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for XiaoESP32S3Gateway IoT resources'

Resources:
  # IoT Thing
  XiaoESP32S3GatewayThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: XiaoESP32S3Gateway

  # IoT Policy
  SmartHouseDevicePolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: SmartHouse-device-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'iot:Connect'
            Resource: 
              - !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:client/${!iot:ClientId}'
            Condition:
              StringEquals:
                'iot:ClientId': 'XiaoESP32S3Gateway'
          - Effect: Allow
            Action:
              - 'iot:Publish'
            Resource: 
              - !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/smarthouse/sensors'
          - Effect: Allow
            Action:
              - 'iot:Subscribe'
            Resource: 
              - !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/smarthouse/*'
          - Effect: Allow
            Action:
              - 'iot:Receive'
            Resource: 
              - !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/smarthouse/*'

  # IoT Rule for processing sensor data
  SmarthouseProcessSensorDataRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: smarthouse_process_sensor_data
      TopicRulePayload:
        Sql: "SELECT deviceId, location, humidity, temperature, battery, rssi, timestamp FROM 'smarthouse/sensors'"
        AwsIotSqlVersion: '2016-03-23'
        Actions:
          - DynamoDB:
              TableName: SmartHouse-sensor-data
              HashKeyField: deviceId
              HashKeyValue: "${deviceId}"
              RangeKeyField: timestamp
              RangeKeyValue: "${timestamp}"
              RoleArn: !GetAtt SmartHouseIoTRole.Arn

  # DynamoDB Table for sensor data
  SmartHouseSensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SmartHouse-sensor-data
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # IAM Role for IoT Rule to access DynamoDB
  SmartHouseIoTRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SmartHouseIoTRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSIoTRuleActions'
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource: !GetAtt SmartHouseSensorDataTable.Arn

  # Note: Certificate creation requires special handling
  # This is a placeholder - certificates typically need to be created separately
  # and then attached to things and policies
