apiVersion: 1
groups:
  - orgId: 1
    name: HumidityAlerts
    folder: SmartHouse
    interval: 1m
    rules:
      - uid: cfcpl1hezkx6oe
        title: HumidityAlerts
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: influxdb-sensors-1
            model:
              intervalMs: 1000
              maxDataPoints: 43200
              query: |
                  from(bucket: "sensors")
                    |> range(start: -5m)
                    |> filter(fn: (r) => r["_measurement"] == "sensor_measurement")
                    |> filter(fn: (r) => r["_field"] == "humidity")
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params: []
                      type: gt
                    operator:
                      type: and
                    query:
                      params:
                          - B
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: mean
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 40
                          - 60
                      type: outside_range
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          description: Humidity level is {{ printf "%.1f" $values.B.Value }}% in {{ $labels.location }}
          summary: |-
              {{ $humidity := $values.B.Value }}
              {{- if (lt $humidity 40.0) -}}
              Low
              {{- else if (gt $humidity 60.0) -}}
              High
              {{- end }} Humidity Detected
        labels:
          measurement: humidity
          severity: warning
        isPaused: false
