apiVersion: 1
templates:
  - orgId: 1
    name: sms_template
    template: |
      {{ define "sms.message" }}
      {{ .Status | toUpper }} [{{ .CommonLabels.severity | toUpper }}]: {{ len .Alerts }} alert(s)
      {{ .CommonAnnotations.summary }}
      {{ range .Alerts }}
      - {{ .Annotations.description }}
      {{ end }}
      {{ end }}
  # Apparently grafana alerts don't support templates for webhooks, so leaving it here as an example
  - orgId: 1
    name: webhook_template
    template: |
      {{ define "webhook.message" }}
      {
        "status": "{{ .Status }}",
        "severity": "{{ .CommonLabels.severity }}",
        "summary": "{{ .CommonAnnotations.summary }}",
        "alertCount": {{ len .Alerts }},
        "alerts": [
          {{- range $index, $alert := .Alerts }}
          {{- if $index }},{{ end }}
          {
            "location": "{{ $alert.Labels.location }}",
            "description": "{{ $alert.Annotations.description }}",
            "value": {{ $alert.Values.B }},
            "timestamp": "{{ $alert.StartsAt }}"
          }
          {{- end }}
        ]
      }
      {{ end }}
