AWSTemplateFormatVersion: '2010-09-09'
Description: |
  SmartHouse
  Cloud backend for SmartHouse project.

Resources:
  XiaoESP32GatewayThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: XiaoESP32Gateway
      AttributePayload:
        Attributes:
          deviceType: ESP32Gateway
          location: SmartHouse

  XiaoESP32GatewayPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-XiaoESP32Gateway-Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: iot:Connect
            Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:client/XiaoESP32Gateway
          - Effect: Allow
            Action: iot:Publish
            Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/smarthouse/sensors
          - Effect: Allow
            Action:
              - iot:Subscribe
              - iot:Receive
            Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/smarthouse/commands/*

  SmartHouseSensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: 'N'
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-sensor-data

  IoTRuleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-IoTRule-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: !GetAtt SmartHouseSensorDataTable.Arn

  SmarthouseProcessSensorDataRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Sub 
        - "${StackName}_sensor_data"
        - StackName: !Join ["_", !Split ["-", !Ref AWS::StackName]]
      TopicRulePayload:
        Sql: SELECT deviceId, location, humidity, temperature, battery, rssi, timestamp
          FROM 'smarthouse/sensors'
        Actions:
          - DynamoDBv2:
              PutItem:
                TableName: !Ref SmartHouseSensorDataTable
              RoleArn: !GetAtt IoTRuleRole.Arn
        RuleDisabled: false

Outputs:
  ThingName:
    Description: IoT Thing Name
    Value: !Ref XiaoESP32GatewayThing
  PolicyName:
    Description: IoT Thing Policy Name
    Value: !Ref XiaoESP32GatewayPolicy
